### ISSUE TITLE
feature request - enable `nrs create` without supplying a xorurl or stdin

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-api#245]
Currently `nrs create` looks for some input, either by passing a xorul in the command or from stdin. If neither is supplied, the `create` command will not successfully run.

It could be useful to allow the user to create "placeholder" NRS urls. Eg, I have some subfolders I want to populate with content but am not ready to add anything to the public name.

**Comment by bochaco** [comment]
I'm closing this a "will not fix" since we have a convention/requirement in NRS that any link from an NRS name should be versioned, so putting a placeholder with a version could be confusing, plus perhaps it doesn't add much benefit than having users to simply provide a dummy versioned URL, in this way the user is explicitly setting a placeholder URL.
