### ISSUE TITLE
cat is confused with ls

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe-api#516]
There is a confusion where cat tries to do both its proper job of concatenation and also listing detail

I suggest the solution is to see those roles as distinct
```
$ safe cat --help
Concatenate FILE(s) to standard output.
```
and 
```
$ safe ls --help
List information about the FILEs (the current directory by default).
```

What cat outputs as detail, is very useful, when it does that - and perhaps all of what exists can be within subcommands of ls, as options for full; or verbose; or default; or filenames only.

For example, these are different outputs where there surely should be consistency.

safe cat safe://testk3
safe cat safe://hello

The first dumps the content, which is fine - there is a text file put there trying to pass that to be visible on the mobile (though that didn't work as mobile doesn't open it).
The second link does a listing output because it happens there is nothing exactly at that location but there is content subordinate to it.

ls == listing
cat == concatenate

**Comment by bochaco** [comment]
Originally, the idea of cat is to show whatever type of content is targeting, if it's a FilesContainer it shows the content of it, if it's resolving to a file it shows the content of a file, if it's a Wallet it shows the content of the wallet, etc. The files ls command works only on FilesContainers, and it outputs showing the hierarchy of the files.

**Comment by davidpbrown** [comment]
Then an option to query --whatis would help, otherwise the command is giving unpredictable output type. If the content was truely a file, that was the spoofed FilesContainer, how would I know the difference?.. daft example but point should be that output type should be known.

Perhaps a file, is not necessarily within a FilesContainer but still I wonder "ls" could and should be listing detail and "cat" should be getting objects as content. That would align so much better with default expectation of naming as cat and ls.

**Comment by davidpbrown** [comment]
Just going to drag dog into this as well.

```safe dog``` doesn't make apparent that there is content at 
```safe dog safe://hnyynyic6eqro83om7gcznj9zq4iscizq6ap71a9iaoc1iii1ijsjyj6mybnc```

where cat notes that
```safe cat safe://hnyynyic6eqro83om7gcznj9zq4iscizq6ap71a9iaoc1iii1ijsjyj6mybnc```

So, an oddity there that for a nrs dog does business but for a xorurl if dog doesn't see anything, you have to also check with cat.. unless you recognise what is nrs and what is url.. which is more work than one listing tool.

Would have expected dog to have noted the content with perhaps a line noting that no registered nrs exists.

On topic - if dog it the metadata tool (and not just ls), then still the point of this issue, is to note that cat is confused with doing listing of metadata and providing concatenate of content.

**Comment by bochaco** [comment]
dog is a inspection tool, that's why it doesn't even output the content, so it's jut to inspect how a url is resolved and what's the target content being resolved from the url provided, I think this will be more clear once we work on the other enhancements we've been discussing in #518 .

The cat is consistent in what it output because it's outputing the target content, so whatever the URL provided is resolved to you will get the content, it's kinda like a browser, it shows you the content that is resolved from a URL regardless what/how it was resolved, if you type an ftp:// url in a browser you may get a list of files, but if you type a url which resolves to an html file you'll get a website rendered. Thus, cat will render the content that has been targetted by the url after all the corresponding resolution has taken place, you may find this confusing because in your filesystem with cat you can only access files or folders but no other type of content like we have on SAFE.

The `safe files ls` subcommand is a subcommand of `safe files` exactly due to this difference, it can act only on FilesContainers (and files somehow), just like any other subcommand of `safe files ls`, this is what makes it different to cat/dog which are generic top level commands that act on any type of content supported by the network.

**Comment by davidpbrown** [comment]
I was expecting [dog is meta data]; [cat is relaying content]; [ls is listing]

You're suggesting something of cat there that is what I would name [get]= get whatever is at the end of xorurl.

I've not looked at what get is expecting that would be a alias for the same.. perhaps I'm wanting [get] and [cat] is more exotic.

I don't know then if [get] will have a wrapper or header to declare what is incoming, given that CLI is liable to be used by applications.. and double queries to dog would seem extra work.

The other way to look at it is that cat to a nrs is a text file but it's a bit odd.

You seem convinced so, I'll close this.

**Comment by bochaco** [comment]
You are right, it's like a get, we used cat as it's broadly known by anyone who ever used a CLI, but it's our own version of it really, to read any type of content from the network. We even used to have the dog fuctionality in the cat command behind a --verbose flag, but people suggested it would be better that goes into a separate command, and since that's is more for inspecting then we came up with the idea of calling it dog as it helps you sniff around the network form a url :smile: , and also because the cat was feeling lonely :D ...so yes, this is just having fun with names and trying to make all this a bit more cool and fun and no just a boring CLI :wink:
